import { Card } from './Card';

export const testDeck = [
    new Card({ suit: 'club', number: 7 }),
    new Card({ suit: 'club', number: 8 }),
    new Card({ suit: 'club', number: 5 }),
    new Card({ suit: 'club', number: 7 }),
    new Card({ suit: 'club', number: 8 }),
    new Card({ suit: 'club', number: 5 }),
    new Card({ suit: 'club', number: 7 }),
    new Card({ suit: 'club', number: 8 }),
    new Card({ suit: 'club', number: 5 }),
    new Card({ suit: 'club', number: 7 }),
    new Card({ suit: 'club', number: 8 }),
    new Card({ suit: 'club', number: 5 }),
    new Card({ suit: 'club', number: 7 }),
    new Card({ suit: 'club', number: 8 }),
    new Card({ suit: 'club', number: 5 }),
    new Card({ suit: 'club', number: 7 }),
    new Card({ suit: 'club', number: 8 }),
    new Card({ suit: 'club', number: 5 }),
    new Card({ suit: 'club', number: 7 }),
    new Card({ suit: 'club', number: 8 }),
    new Card({ suit: 'club', number: 5 }),
    new Card({ suit: 'club', number: 7 }),
    new Card({ suit: 'club', number: 8 }),
    new Card({ suit: 'club', number: 5 }),
    new Card({ suit: 'club', number: 7 }),
    new Card({ suit: 'club', number: 8 }),
    new Card({ suit: 'club', number: 10 }),
    new Card({ suit: 'club', faceCard: 'ace', number: 11 }),
];
